### ISSUE TITLE
Networking through modem emulation over UART

### ISSUE THREAD

**Issue by driver1998** [driver1998/bsp#1]
This is a mega thread for modem emulation and networking stuff.

Instructions is moved to wiki: https://github.com/driver1998/bsp/wiki/Modem-Emulation-and-Networking.

**Comment by driver1998** [comment]
1.Set up a PPP-over-Telnet service
configure pppd by editing the following files:
`/etc/ppp/options`
```
# We will be doing PPP over Telnet - disable serial control.
local

# Terminate connection if remote side stops responding.
lcp-echo-interval 30
lcp-echo-failure 4

# Debug adds a lot of detail into the system logs regarding PPP negotiation.
# This is helpful in debugging client issues.
debug

# IP addresses to use in local:remote format.  We use NAT to share
# the Wi-Fi connection, make sure these are outside of your real subnet.
192.168.100.1:192.168.100.2

# Other sensible options
asyncmap 0
passive
noipx
```

**Comment by driver1998** [comment]
# Set up NAT and routing for Internet access
Here we assume your network card to Internet is eth0.

First, enable IPv4 forwarding with the following command.
```
sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
```

Then enable NAT for your RPi.
iptables -t nat -A POSTROUTING –o eth0 –s 192.168.100.0/24 –j MASQUERADE

**Comment by driver1998** [comment]
# Finally, Set up tcpser for modem emulation

Build tcpser, then run it with the following command:
```
sudo tcpser -s 115200 -d /dev/ttyUSB0 -l4 -i '&K0' -n "30624700=127.0.0.1:4074"
```

`-s 115200` - Connection speed, up to 921600bps
`-d /dev/ttyUSB0` - Device file for your USB to TTL adapter
`-l4` - Debug level 4, for something to look at :)
`-i '&K0'` - Disable flow control
`-n "30624700=127.0.0.1:4074"` - Phone book, which is a list of pseudo phone numbers to dial. So when we dial 30624700, 127.0.0.1:4074 will be connected.

**Comment by Googulator** [comment]
Even better, use "Communications cable between two computers" from mdmhayes.inf with the same AMD64 -> ARM64 mod, and a Windows host to share the connection from.

More details here: https://serverfault.com/questions/130435/how-to-set-up-a-serial-connection-to-a-windows-7-computer

**Comment by driver1998** [comment]
@Googulator I tried, but I can only get about 9600bps, that is way slower....

**Comment by Googulator** [comment]
Did you edit rasphone.pbk to set the correct connection type?

**Comment by driver1998** [comment]
Can you provide some more details about that?

**Comment by driver1998** [comment]
Closing this issue since Ethernet is working now.
